### The Operator Form of3H (3He)  and its Spin Structure

In [2]:
import numpy as np
import os


### 读取phi的数据
### $n_q*n_p*n_x = 36*40*8 = 11520$

In [3]:
def fortran_to_float(s):
    """将Fortran科学计数法字符串转换为浮点数"""
    return float(s.replace('D', 'E'))

def read_grid_file(filename):
    """读取网格文件 (qpx 或 wqpx)"""
    data_dir = '/home/mengzhu/mywork/He3_Au_work/data'
    filename = os.path.join(data_dir, filename)
    with open(filename, 'r') as f:
        lines = [line.strip() for line in f if line.strip()]
    
    # 读取网格点数
    n_q = int(lines[0])
    q_values = np.array([fortran_to_float(line) for line in lines[1:n_q+1]])
    
    n_p = int(lines[n_q+1])
    p_values = np.array([fortran_to_float(line) for line in lines[n_q+2:n_q+2+n_p]])
    
    n_x = int(lines[n_q+2+n_p])
    x_values = np.array([fortran_to_float(line) for line in lines[n_q+3+n_p:n_q+3+n_p+n_x]])
    
    return q_values, p_values, x_values



In [4]:
# 读取网格坐标和权重
q_grid, p_grid, x_grid = read_grid_file('qpx.dat')
w_q, w_p, w_x = read_grid_file('wqpx.dat')  # 积分权重

In [5]:
q_grid

array([1.8257573e-03, 9.6385537e-03, 2.3771042e-02, 4.4358438e-02,
       7.1593472e-02, 1.0573040e-01, 1.4708706e-01, 1.9604687e-01,
       2.5306056e-01, 3.1864724e-01, 3.9339432e-01, 4.7795521e-01,
       5.7304378e-01, 6.7942387e-01, 7.9789156e-01, 9.2924745e-01,
       1.0742550e+00, 1.2335809e+00, 1.4077111e+00, 1.5968390e+00,
       1.8007189e+00, 2.0184848e+00, 2.2484366e+00, 2.4878075e+00,
       2.7325409e+00, 2.9771210e+00, 3.2145238e+00, 3.4363641e+00,
       3.6333060e+00, 3.7957701e+00, 3.9148936e+00, 3.9836280e+00,
       4.4165911e+00, 5.9800569e+00, 8.0199431e+00, 9.5834089e+00])

In [6]:
p_grid

array([1.8257573e-03, 9.6385537e-03, 2.3771042e-02, 4.4358438e-02,
       7.1593472e-02, 1.0573040e-01, 1.4708706e-01, 1.9604687e-01,
       2.5306056e-01, 3.1864724e-01, 3.9339432e-01, 4.7795521e-01,
       5.7304378e-01, 6.7942387e-01, 7.9789156e-01, 9.2924745e-01,
       1.0742550e+00, 1.2335809e+00, 1.4077111e+00, 1.5968390e+00,
       1.8007189e+00, 2.0184848e+00, 2.2484366e+00, 2.4878075e+00,
       2.7325409e+00, 2.9771210e+00, 3.2145238e+00, 3.4363641e+00,
       3.6333060e+00, 3.7957701e+00, 3.9148936e+00, 3.9836280e+00,
       4.2184058e+00, 5.1183344e+00, 6.6095717e+00, 8.4911095e+00,
       1.0508891e+01, 1.2390428e+01, 1.3881666e+01, 1.4781594e+01])

In [7]:
x_grid

array([-0.96028986, -0.79666648, -0.52553241, -0.18343464,  0.18343464,
        0.52553241,  0.79666648,  0.96028986])

In [8]:
def read_phi_file(filename, n_q=36, n_p=40, n_x=8):
    """读取phi文件并按 (q, p, x) 顺序重构3D数组"""
    with open(filename, 'r') as f:
        data = np.array([fortran_to_float(line.strip()) for line in f if line.strip()])
    return data.reshape((n_x, n_p, n_q)).transpose(2, 1, 0)  # 调整为 (q, p, x)



In [9]:
# 加载所有phi_i
data_dir = '/home/mengzhu/mywork/He3_Au_work/data'
phi_grids = {}
for i in range(1, 9):
    file_path = os.path.join(data_dir, f'he3.av18.phi{i}.dat')
    phi_grids[f'phi{i}'] = read_phi_file(file_path)

In [10]:
phi_grids

{'phi1': array([[[ 4.1074035e+00,  4.1074035e+00,  4.1074036e+00, ...,
           4.1074036e+00,  4.1074035e+00,  4.1074035e+00],
         [ 4.1036800e+00,  4.1036801e+00,  4.1036803e+00, ...,
           4.1036803e+00,  4.1036801e+00,  4.1036800e+00],
         [ 4.0841191e+00,  4.0841191e+00,  4.0841191e+00, ...,
           4.0841191e+00,  4.0841191e+00,  4.0841191e+00],
         ...,
         [ 4.4836783e-06,  4.4836784e-06,  4.4836784e-06, ...,
           4.4836784e-06,  4.4836784e-06,  4.4836783e-06],
         [-8.9510273e-07, -8.9510271e-07, -8.9510268e-07, ...,
          -8.9510268e-07, -8.9510271e-07, -8.9510273e-07],
         [-7.4885786e-07, -7.4885783e-07, -7.4885778e-07, ...,
          -7.4885778e-07, -7.4885783e-07, -7.4885786e-07]],
 
        [[ 4.1051976e+00,  4.1051976e+00,  4.1051976e+00, ...,
           4.1051976e+00,  4.1051976e+00,  4.1051976e+00],
         [ 4.1014735e+00,  4.1014739e+00,  4.1014744e+00, ...,
           4.1014744e+00,  4.1014739e+00,  4.1014735e+00],

### 插值连续化phi

In [11]:
from scipy.interpolate import RegularGridInterpolator

phi_interps = {}
for i in range(1, 9):
    phi_interps[f'phi{i}'] = RegularGridInterpolator(
        (q_grid, p_grid, x_grid),
        phi_grids[f'phi{i}'],
        bounds_error=False,
        fill_value=0.0
    )

In [12]:
# 检查第一个网格点 (q[0], p[0], x[0])
print("phi1 at first grid point:", phi_grids['phi1'][0, 0, 0])
print("Interpolated value:", phi_interps['phi1']((q_grid[0], p_grid[0], x_grid[0])))

phi1 at first grid point: 4.1074035
Interpolated value: 4.1074035


In [13]:
# 数值积分: ∫ phi1^2 dq dp dx
norm = np.sum(phi_grids['phi1']**2 * w_q[:, None, None] * w_p[None, :, None] * w_x[None, None, :])
print("Norm of phi1:", norm)

Norm of phi1: 2.2692769363663987


In [14]:
# 检查插值是否必要：尝试在非网格点求值
p_test, q_test, x_test = 1.23, 2.34, 0.5  # 非精确网格点

# 若不插值，只能找到最近的网格点
idx_p = np.argmin(np.abs(p_grid - p_test))
idx_q = np.argmin(np.abs(q_grid - q_test))
idx_x = np.argmin(np.abs(x_grid - x_test))
approx_val = phi_grids['phi1'][idx_q, idx_p, idx_x]  # 近似值（可能不精确）

# 使用插值获得精确值
interp_val = phi_interps['phi1']([q_test, p_test, x_test])

print(f"Nearest grid value: {approx_val}")
print(f"Interpolated value: {interp_val}")

Nearest grid value: -0.00026694668
Interpolated value: [-0.00033148]


In [15]:
# 积分常数函数1，结果应为体积 (Δq Δp Δcosθ)
integral_1 = np.sum(w_q[:, None, None] * w_p[None, :, None] * w_x[None, None, :])
print("Volume integral:", integral_1)  # 应接近 (q_max - q_min) * (p_max - p_min) * 2 ≈ 10*15*2=300

Volume integral: 300.00000095499996


In [16]:
def psi_rs(r, s, theta_rs, phi_interps, q_grid, p_grid, x_grid, w_q, w_p, w_x):
    """计算坐标空间波函数（离散积分法，避免直接调用nquad）"""
    psi = 0 + 0j
    for i_q, q in enumerate(q_grid):
        for i_p, p in enumerate(p_grid):
            for i_x, x in enumerate(x_grid):
                # 相位因子 e^{i(pr + qs)}
                pr = p * r * np.sqrt(1 - x**2)  # p·r = p r sinθ_pq (简化假设)
                qs = q * s * np.cos(theta_rs)    # q·s = q s cosθ_qs
                phase = np.exp(1j * (pr + qs))
                
                # 波函数求和
                phi_sum = sum(phi_interps[f'phi{i}']((q, p, x)) for i in range(1, 9))
                
                # 加权积分
                psi += phase * phi_sum * w_q[i_q] * w_p[i_p] * w_x[i_x] * p**2 * q**2
    return psi

# 示例计算
r, s, theta_rs = 1.0, 0.5, 0.0
psi_val = psi_rs(r, s, theta_rs, phi_interps, q_grid, p_grid, x_grid, w_q, w_p, w_x)

In [17]:
psi_val

(0.2929503597866554+0.21128810211768986j)

In [18]:
from multiprocessing import Pool
from tqdm import tqdm

# 定义坐标网格
# r_points = np.linspace(0, 5, 20)  # fm
# s_points = np.linspace(0, 5, 20)
# theta_points = np.linspace(0, np.pi, 10)
r_points = np.linspace(0, 2, 10)  # fm
s_points = np.linspace(0, 2, 10)
theta_points = np.linspace(0, np.pi, 5)

# 初始化密度矩阵
density = np.zeros((len(r_points), len(s_points), len(theta_points)))

def compute_point(args):
    i, j, k, r, s, theta = args
    psi = psi_rs(r, s, theta, phi_interps, q_grid, p_grid, x_grid, w_q, w_p, w_x)
    return (i, j, k, np.abs(psi)**2)

tasks = [(i, j, k, r, s, theta) 
         for i, r in enumerate(r_points)
         for j, s in enumerate(s_points)
         for k, theta in enumerate(theta_points)]

with Pool(processes=20) as pool:  # 使用4个核心
    for result in tqdm(pool.imap(compute_point, tasks), total=len(tasks)):
        i, j, k, val = result
        density[i, j, k] = val

100%|█████████████████████████████████████████| 500/500 [03:21<00:00,  2.49it/s]


In [19]:
norm = np.sum(density * np.diff(r_points)[0] * np.diff(s_points)[0] * np.diff(theta_points)[0])
print("Normalization:", norm)

Normalization: 0.7640470066948211


In [20]:
density

array([[[7.73768729e-02, 7.73768729e-02, 7.73768729e-02, 7.73768729e-02,
         7.73768729e-02],
        [7.19106625e-02, 7.46099301e-02, 7.73768729e-02, 7.46099301e-02,
         7.19106625e-02],
        [5.72233435e-02, 6.67232977e-02, 7.73768729e-02, 6.67232977e-02,
         5.72233435e-02],
        [3.84639148e-02, 5.50322894e-02, 7.73768729e-02, 5.50322894e-02,
         3.84639148e-02],
        [2.19563888e-02, 4.16796946e-02, 7.73768729e-02, 4.16796946e-02,
         2.19563888e-02],
        [1.09763130e-02, 2.90277304e-02, 7.73768729e-02, 2.90277304e-02,
         1.09763130e-02],
        [5.05253049e-03, 1.87569518e-02, 7.73768729e-02, 1.87569518e-02,
         5.05253049e-03],
        [2.70840431e-03, 1.13947247e-02, 7.73768729e-02, 1.13947247e-02,
         2.70840431e-03],
        [2.54915116e-03, 6.61277959e-03, 7.73768729e-02, 6.61277959e-03,
         2.54915116e-03],
        [2.79928431e-03, 3.85369347e-03, 7.73768729e-02, 3.85369347e-03,
         2.79928431e-03]],

       [