In [1]:
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import Image

$$\Psi_{d}=\psi_{S}+\psi_{D}=\frac{u(r)}{r} Y_{101}^{1}+\frac{w(r)}{r} Y_{121}^{1}$$

\begin{array}{l}u(r)=\sum_{i=1}^{20} r^{3/2}A_{i} \exp \left(-a_{i} r^{3}\right) \\ w(r)=r \sum_{i=1}^{20} B_{i} \exp \left(-b_{i} r^{3}\right)\end{array}

In [2]:
table=np.array([[1, -2.31737065809, 0.35274596179, -0.16442140495, 4.27551981801],
                [2, 0.02659110800, 0.00732058085, 0.02868983216 ,0.02949360502],
                [3, -0.28877337807, 5.38000986025, 0.00074392415, 0.00062004296],
                [4, 0.99922786191, 0.36067988379, 0.05707754763, 0.09089766773],
                [5, 0.11094070754, 0.06921749879, 0.01167238661, 0.00953758791],
                [6, 0.01077521733, 0.00225041184, 0.00370587438, 0.00281824630],
                [7, 0.00274077964, 0.00052965934, 0.08509685731, 0.30274669392],
                [8, 0.65409540449, 0.26723780768,0,0],
                [9, 0.99185931871, 0.41270669565,0,0],
                [10, 0.05693893648, 0.02247865903,0,0]])

$$Y_{Jl1}(\theta,\phi)=\sum_{m=-l}^{l}\sum_{m'=-1}^{1}C_{l1}(J,M;m,m')Y_{lm}(\theta,\phi)\chi_{m'}$$

\begin{equation} \label{eq1}
\begin{split}
|\psi(r)|^2 & =(\frac{u(r)}{r} Y_{101}^{1}+\frac{w(r)}{r} Y_{121}^{1})^{*}（\frac{u(r)}{r} Y_{101}^{1}+\frac{w(r)}{r}Y_{121}^{1}） \\
 & = \frac{u^2(r)}{r^2}(Y_{101}^{1})^*Y_{101}^{1}+\frac{u(r)w(r)}{r^2}(Y_{101}^{1})^*Y_{121}^{1}+\frac{w(r)u(r)}{r^2}(Y_{121}^{1})^*Y_{101}^{1}+\frac{w^2(r)}{r^2}(Y_{121}^{1})^*Y_{121}^{1} \\
 & = \frac{u^2(r)}{4\pi r^2} +\frac{u(r)w(r)}{r^2}\frac{1}{\sqrt{\pi}}\left[\sqrt{\frac{1}{16\pi}}(3\cos^2\theta-1)+\sqrt{\frac{3}{8\pi}}sin^2\theta\cos(2\phi)\right]\\
 &+ \frac{w^2(r)}{r^2}\left[\frac{1}{16\pi}(3\cos^2\theta-1)^2+\frac{3}{2\pi}\sin^2\theta\cos^2\theta\sin^2\phi+\frac{3}{8\pi}\sin^4\theta\cos^2(2\phi)+\frac{\sqrt 3}{4\pi\sqrt 2}\sin^2\theta\cos(2\phi)(3\cos^2\theta-1)\right]
\end{split}
\end{equation}

\begin{equation} 
\begin{split}
|\psi(r)|^2d^3r & = (\frac{u(r)}{r} Y_{101}^{1}+\frac{w(r)}{r} Y_{121}^{1})^{*}（\frac{u(r)}{r} Y_{101}^{1}+\frac{w(r)}{r}Y_{121}^{1}）d^3r \\
& = \left[\frac{u^2(r)}{r^2}(Y_{101}^{1})^*Y_{101}^{1}+\frac{u(r)w(r)}{r^2}(Y_{101}^{1})^*Y_{121}^{1}+\frac{w(r)u(r)}{r^2}(Y_{121}^{1})^*Y_{101}^{1}+\frac{w^2(r)}{r^2}(Y_{121}^{1})^*Y_{121}^{1}\right]d^3r \\
& = \frac{u^2(r)}{4\pi r^2}r^2drd\Omega+\frac{u(r)w(r)}{r^2}\frac{1}{\sqrt{\pi}}\left[\sqrt{\frac{1}{16\pi}}(3\cos^2\theta-1)+\sqrt{\frac{3}{8\pi}}sin^2\theta\cos(2\phi)\right]r^2drd\Omega \\
&+\frac{w^2(r)}{r^2}\left[\frac{1}{16\pi}(3\cos^2\theta-1)^2+\frac{3}{2\pi}\sin^2\theta\cos^2\theta\sin^2\phi+\frac{3}{8\pi}\sin^4\theta\cos^2(2\phi)+\frac{\sqrt 3}{4\pi\sqrt 2}\sin^2\theta\cos(2\phi)(3\cos^2\theta-1)\right]r^2drd\Omega \\
& = \frac{u^2(r)}{4\pi }dr\sin\theta d\theta d\phi+u(r)w(r)\frac{1}{\sqrt{\pi}}\left[\sqrt{\frac{1}{16\pi}}(3\cos^2\theta-1)+\sqrt{\frac{3}{8\pi}}sin^2\theta\cos(2\phi)\right]dr\sin\theta d\theta d\phi \\
&+w^2(r)\left[\frac{1}{16\pi}(3\cos^2\theta-1)^2+\frac{3}{2\pi}\sin^2\theta\cos^2\theta\sin^2\phi+\frac{3}{8\pi}\sin^4\theta\cos^2(2\phi)+\frac{\sqrt 3}{4\pi\sqrt 2}\sin^2\theta\cos(2\phi)(3\cos^2\theta-1)\right]dr\sin\theta d\theta d\phi
\end{split}
\end{equation}

### 定义三个部分的概率密度分布

In [3]:
def p1(r1,theta1):
    return u(r1)**2/(4*np.pi) * np.sin(theta1)

In [4]:
def p2(r2,theta2,phi2):
#     A = 0.3162277660168378
    return u(r2) * w(r2)/(np.pi) * ( np.sqrt(1/16) * (3 * np.cos(theta2)**2 - 1)
                                +np.sqrt(3/8) * np.sin(theta2)**2 * np.cos(2*phi2) ) * np.sin(theta2)

In [5]:
def p3(r3,theta3,phi3):
    return w(r3)**2 * ( 1/(16*np.pi) * (3 * np.cos(theta3)**2 - 1)**2 
                        + 3/(2*np.pi) * np.sin(theta3)**2 * np.cos(theta3)**2 * np.sin(phi3)**2
                        +3/(8*np.pi) * np.sin(theta3)**4 * np.cos(2*phi3)**2
                        +np.sqrt(3)/(4*np.pi*np.sqrt(2))
                       *np.sin(theta3)**2 * np.cos(2*phi3) * (3*np.cos(theta3)**2 - 1) ) * np.sin(theta3)

In [6]:
#定义总的概率密度函数
def p(r,theta,phi):
    return p1(r1=r,theta1=theta) + p2(r2=r,theta2=theta,phi2=phi) + p3(r3=r,theta3=theta,phi3=phi)

In [7]:
def rejection_sampling(pdf, n=1000, ymax=1, xmin=0, xmax_theta=np.pi,xmax_phi=2*np.pi,xmax_r=25):
    samples_r = np.zeros(n, dtype=np.float32)
    samples_theta = np.zeros(n, dtype=np.float32)
    samples_phi = np.zeros(n, dtype=np.float32)
    i = 0
    while i < n:
        r = xmin + (xmax_r - xmin) * np.random.rand()
        theta = xmin + (xmax_theta - xmin) * np.random.rand()
        phi = xmin + (xmax_phi - xmin) * np.random.rand()
        y = ymax * np.random.rand()
        if y < pdf(r,theta,phi):   # accept
            samples_r[i] = r
            samples_theta[i] = theta
            samples_phi[i] = phi
            i = i + 1
    
    return samples_r,samples_theta,samples_phi

In [8]:
# d_sam_r_theta_phi_100000 = rejection_sampling(pdf=p, n=100000, ymax=1, xmin=0, xmax_theta=np.pi,xmax_phi=2*np.pi,xmax_r=20)

In [9]:
# np.savetxt("d_sam_r_theta_phi_100000.dat", d_sam_r_theta_phi_100000)

### 读取采样出来的数据

In [10]:
d_sample = np.loadtxt("/home/mengzhu/mywork/denteron_to_Au_collide_writing/d_sam_r_theta_phi_100000.dat")

In [11]:
d_sample.shape

(3, 100000)

In [12]:
#抽样出来的r,theta,phi
r_sam = d_sample[0]
theta_sam = d_sample[1]
phi_sam = d_sample[2]

In [13]:
#计算抽样出的绝对核子坐标
x_sam = r_sam * np.sin(theta_sam) * np.cos(phi_sam)
y_sam = r_sam * np.sin(theta_sam) * np.sin(phi_sam)
z_sam = r_sam * np.cos(theta_sam)

xp = 0 - x_sam/2
yp = 0 - y_sam/2
zp = 0 - z_sam/2

xn = x_sam - x_sam/2
yn = y_sam - y_sam/2
zn = z_sam - z_sam/2

In [14]:
np.random.randint(2)

1

In [15]:
sam_data_real_p = []
sam_data_real_t = []

for i in range(50000):
    random_number1 = np.random.randint(2)
    random_number2 = 1 - random_number1 
    
    p1 = [xp[i],yp[i],zp[i],random_number1,random_number1]
    n1 = [xn[i],yn[i],zn[i],random_number2,random_number2]
    sam_data_real_p.append(p1) 
    sam_data_real_p.append(n1)
    
    p2 = [xp[i+50000],yp[i+50000],zp[i+50000],random_number1,random_number1]
    n2 = [xn[i+50000],yn[i+50000],zn[i+50000],random_number2,random_number2]
    sam_data_real_t.append(p2) 
    sam_data_real_t.append(n2)
    

In [32]:
sam_data_real_p

[[-0.8165764134783083, 0.3026327488276665, 0.6443789411274862, 1, 1],
 [0.8165764134783083, -0.3026327488276665, -0.6443789411274862, 0, 0],
 [-1.3562237834444695, -1.3476560241710402, 1.4476278615199414, 1, 1],
 [1.3562237834444695, 1.3476560241710402, -1.4476278615199414, 0, 0],
 [-0.09001182463505909, 0.35272112720041354, 0.8571457071860527, 1, 1],
 [0.09001182463505909, -0.35272112720041354, -0.8571457071860527, 0, 0],
 [1.9072113463118452, 1.1055538180367632, 0.4346319104068173, 1, 1],
 [-1.9072113463118452, -1.1055538180367632, -0.4346319104068173, 0, 0],
 [1.2266317433704588, 0.48294779391260273, 0.6568183711183316, 0, 0],
 [-1.2266317433704588, -0.48294779391260273, -0.6568183711183316, 1, 1],
 [-0.45392833932429066, 2.1105833642915774, 2.8714536337909613, 0, 0],
 [0.45392833932429066, -2.1105833642915774, -2.8714536337909613, 1, 1],
 [1.1103203270032977, -0.44482418196462675, 2.11462425368932, 0, 0],
 [-1.1103203270032977, 0.44482418196462675, -2.11462425368932, 1, 1],
 [0.752

In [16]:
np.array(sam_data_real_p)

array([[-8.16576413e-01,  3.02632749e-01,  6.44378941e-01,
         1.00000000e+00,  1.00000000e+00],
       [ 8.16576413e-01, -3.02632749e-01, -6.44378941e-01,
         0.00000000e+00,  0.00000000e+00],
       [-1.35622378e+00, -1.34765602e+00,  1.44762786e+00,
         1.00000000e+00,  1.00000000e+00],
       ...,
       [ 1.78093795e+00,  3.35250577e-01,  7.97049343e-01,
         1.00000000e+00,  1.00000000e+00],
       [ 1.60061561e+00, -7.72251925e-04,  7.83522046e-01,
         1.00000000e+00,  1.00000000e+00],
       [-1.60061561e+00,  7.72251925e-04, -7.83522046e-01,
         0.00000000e+00,  0.00000000e+00]])

In [17]:
np.array(sam_data_real_p).shape

(100000, 5)

In [18]:
len(sam_data_real_p)

100000

In [19]:
fmt =  '%1.8f', '%1.8f', '%1.8f', '%d','%d'
np.savetxt("smash_d_100000_p.dat", sam_data_real_p,fmt = fmt)

In [20]:
fmt =  '%1.8f', '%1.8f', '%1.8f', '%d','%d'
np.savetxt("smash_d_100000_t.dat", sam_data_real_t,fmt = fmt)

### 导出trento产生的坐标信息

In [21]:
#导出trento产生的坐标信息
data_trento = np.loadtxt("/home/mengzhu/trento_alpha_cluster/build/deuteron_r.dat")

In [22]:
data_trento.shape

(200000, 3)

In [23]:
data_trento[0,0]

-0.785783

In [24]:
trento_data_real = []
# trento_data_real_t = []
i = 0
for j in range(100000):
    
    random_number1 = np.random.randint(2)
    random_number2 = 1 - random_number1 
    
    p1 = [data_trento[i,0],data_trento[i,1],data_trento[i,2],random_number1,random_number1]
    n1 = [data_trento[i+1,0],data_trento[i+1,1],data_trento[i+1,2],random_number2,random_number2]
    trento_data_real.append(p1) 
    trento_data_real.append(n1)
    
#     p2 = [data_trento[i+50000,0],data_trento[i+50000,1],data_trento[i+50000,2],random_number1,random_number1]
#     n2 = [data_trento[i+50001,0],data_trento[i+50001,1],data_trento[i+50001,2],random_number2,random_number2]
#     trento_data_real_t.append(p2) 
#     trento_data_real_t.append(n2)
    i = i + 2

In [25]:
len(trento_data_real)

200000

In [26]:
trento_data_real_p = np.array(trento_data_real[0:100000])

In [27]:
trento_data_real_p

array([[-0.785783, -0.320363,  0.460551,  1.      ,  1.      ],
       [ 0.785783,  0.320363, -0.460551,  0.      ,  0.      ],
       [ 0.114863,  0.859303, -0.704949,  1.      ,  1.      ],
       ...,
       [ 1.009   , -0.490294, -0.624584,  1.      ,  1.      ],
       [-1.15432 , -2.22767 , -0.336018,  0.      ,  0.      ],
       [ 1.15432 ,  2.22767 ,  0.336018,  1.      ,  1.      ]])

In [28]:
fmt =  '%1.8f', '%1.8f', '%1.8f', '%d','%d'
np.savetxt("trento_d_100000_p.dat", trento_data_real_p,fmt = fmt)

In [29]:
trento_data_real_t = np.array(trento_data_real[100000:])

In [30]:
trento_data_real_t

array([[-0.284002, -0.357011, -1.54583 ,  0.      ,  0.      ],
       [ 0.284002,  0.357011,  1.54583 ,  1.      ,  1.      ],
       [-2.26933 ,  0.998697, -2.51635 ,  1.      ,  1.      ],
       ...,
       [ 4.41076 ,  1.49772 , -2.54855 ,  1.      ,  1.      ],
       [ 0.439084, -1.52007 , -1.15577 ,  1.      ,  1.      ],
       [-0.439084,  1.52007 ,  1.15577 ,  0.      ,  0.      ]])

In [31]:
fmt =  '%1.8f', '%1.8f', '%1.8f', '%d','%d'
np.savetxt("trento_d_100000_t.dat", trento_data_real_t,fmt = fmt)